//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: craft.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_craft_H__
#define __WDR_craft_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "craft_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_TEXT 10000
#define ID_IPV4_DEST 10001
#define ID_IPV4_SOURCE 10002
#define ID_IPV4_AUTO_SOURCE 10003
#define ID_IPV4_FLAG_MF 10004
#define ID_IPV4_FLAG_LF 10005
#define ID_IPV4_PROTOCOLS 10006
#define ID_IPV4_PROTO_OTHER 10007
#define ID_IPV4_LENGTH_TXT 10008
#define ID_IPV4_LENGTH 10009
#define ID_IPV4_OVERRIDE_LENGTH 10010
#define ID_IPV4_EDIT_OPTIONS 10011
wxSizer *IPv4( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_NOTEBOOK 10012
#define ID_IPV4_HEX 10013
#define ID_SEND_PACKET 10014
#define ID_SEND_COUNT 10015
#define ID_SEND_INFINITE 10016
#define ID_LINE 10017
#define ID_SEND_INTERVAL 10018
#define ID_SEND_INTERVAL_RANDOM 10019
wxSizer *Main( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TCP_SOURCE_PORT 10020
#define ID_TCP_SOURCE 10021
#define ID_TCP_DEST_PORT 10022
#define ID_TCP_DEST 10023
#define ID_TCP_SEQ 10024
#define ID_TCP_SEQ_RANDOM 10025
#define ID_TCP_ACK 10026
#define ID_TCP_ACK_RANDOM 10027
#define ID_TCP_R1 10028
#define ID_TCP_R2 10029
#define ID_TCP_R3 10030
#define ID_TCP_R4 10031
#define ID_TCP_R5 10032
#define ID_TCP_R6 10033
#define ID_TCP_HDR_LEN_TEXT 10034
#define ID_TCP_HDR_LEN 10035
#define ID_TCP_HDR_LEN_OVERRIDE 10036
#define ID_TCP_WINDOW_SIZE 10037
#define ID_TCP_URG_PTR 10038
#define ID_TCP_FLAG_URG 10039
#define ID_TCP_FLAG_ACK 10040
#define ID_TCP_FLAG_PSH 10041
#define ID_TCP_FLAG_RST 10042
#define ID_TCP_FLAG_SYN 10043
#define ID_TCP_FLAG_FIN 10044
#define ID_TCP_OPTIONS_EDIT 10045
#define ID_TCP_CHECKSUM 10046
#define ID_TCP_CHECKSUM_OVERRIDE 10047
wxSizer *IPV4_TCP( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LIST_LOG 10048
wxSizer *Log( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
